server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway
            client-secret: ${GATEWAY_CLIENT_SECRET:LPX43LoHek5l6iCGHPvQTNpyjK2ms07C}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${GATEWAY_AUTHSERVER_ISSUER_URI:http://localhost:9000/realms/local}
            user-name-attribute: preferred_username
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: http://frontend:[*],http://gateway:[*]
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: get_demo
          uri: ${GATEWAY_BENEFICIARIES_URI:http://beneficiaries:8080}
          predicates:
            - Method=GET
            - Path=/api/v1/beneficiaries/demo
          filters:
            - TokenRelay=
            - SaveSession
        - id: post_demo
          uri: ${GATEWAY_BENEFICIARIES_URI:http://beneficiaries:8080}
          predicates:
            - Method=POST
            - Path=/api/v1/beneficiaries/demo
        - id: countries_demo
          uri: ${GATEWAY_BENEFICIARIES_URI:http://beneficiaries:8080}
          predicates:
            - Method=GET
            - Path=/api/v1/countries
          filters:
            - TokenRelay=
            - SaveSession
        - id: frontend
          uri: ${GATEWAY_FRONTEND_URI:http://frontend:4200}
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
            - SaveSession
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:redis}
      port: ${GATEWAY_REDIS_PORT:6379}
  session:
    store-type: redis

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO