### project ###

project:
  name: product-module

### server ###

server:
  port: 7003
  use-forward-headers: true
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
    include-binding-errors: always

### logging ###

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.data.mongodb: debug

### spring ###

spring:
  main:
    banner-mode: off
    log-startup-info: true
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      username: ${PRODUCT_MODULE_MONGODB_USER}
      password: ${PRODUCT_MODULE_MONGODB_PASSWORD}
      authentication-database: ${PRODUCT_MODULE_MONGODB_AUTH_DB}
      database: ${PRODUCT_MODULE_MONGODB_DB}
      port: ${PRODUCT_MODULE_MONGODB_PORT}
      host: ${PRODUCT_MODULE_MONGODB_HOST}
      auto-index-creation: true

### actuator ###

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health