server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${BENEFICIARIES_HIBERNATE_DDL_AUTO:update}
      show-sql: ${BENEFICIARIES_HIBERNATE_SHOW_SQL:true}
  datasource:
    url: ${BENEFICIARIES_DATASOURCE_URL:jdbc:postgresql://postgres/beneficiaries}
    username: ${BENEFICIARIES_POSTGRES_USERNAME:beneficiaries}
    password: ${BENEFICIARIES_POSTGRES_PASSWORD:password}
#    initialization-mode: always
#    initialize: true
#    schema: classpath:/schema.sql
#    continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BENEFICIARIES_AUTHSERVER_ISSUER_URI:http://keycloak:9000/realms/local}

props:
  jwksUri: ${BENEFICIARIES_JWKS_URI:http://localhost:9000/realms/local/protocol/openid-connect/certs}