### project ###

project:
  name: operator-module

### server ###

server:
  port: 7001
  use-forward-headers: true
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
    include-binding-errors: always

### logging ###

logging:
  level:
    root: info
    org.springframework.web: debug
    #file:
    #name: path\to\log\folder\moonbox-operator-module.log

### spring ###

spring:
  main:
    banner-mode: off
    log-startup-info: true
  output:
    ansi:
      enabled: always

### actuator ###

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

### keycloak ###

keycloak:
  realm: moonbox
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  ssl-required: external
  use-resource-role-mappings: false
  resource: ${OPERATOR_MODULE_KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${OPERATOR_MODULE_KEYCLOAK_CLIENT_SECRET}