### project ###

project:
  name: operator-module

### server ###

server:
  port: 7001
  use-forward-headers: true
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
    include-binding-errors: always

### logging ###

logging:
  level:
    root: info
    org.springframework.web: debug
    #file:
    #name: C:\Users\Giovanni\temporary\logs\moonbox-operator-module.log

### spring ###

spring:
  main:
    banner-mode: off
    log-startup-info: true
  output:
    ansi:
      enabled: always

### actuator ###

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    redis:
      enabled: true
    mongo:
      enabled: true
  trace:
    http:
      enabled: true
      include:
        - RESPONSE_HEADERS
        - REQUEST_HEADERS
        - REMOTE_ADDRESS
        - TIME_TAKEN
        - PRINCIPAL
        - AUTHORIZATION_HEADER
        - COOKIE_HEADERS
        - SESSION_ID
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, httptrace

### keycloak ###

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  ssl-required: external
  use-resource-role-mappings: false
  resource: ${OPERATOR_MODULE_KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${OPERATOR_MODULE_KEYCLOAK_CLIENT_SECRET}